import SwiftUI

struct DisclaimerView: View {
    var body: some View {
        ScrollView {
            VStack(spacing: 24) {
                headerBadge(icon: "exclamationmark.triangle.fill", color: .orange, title: "Disclaimers", date: "Please read carefully")

                importantDisclaimer

                PolicyCard(icon: "music.mic", iconColor: .red, title: "AI Feedback Disclaimer") {
                    VStack(alignment: .leading, spacing: 10) {
                        Text("The AI-powered practice feedback in KITB uses artificial intelligence to analyze audio recordings and provide general observations about your playing. This feedback is:")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)

                        VStack(alignment: .leading, spacing: 8) {
                            DisclaimerBullet(text: "Generated by AI algorithms and may not be perfectly accurate")
                            DisclaimerBullet(text: "Not a substitute for evaluation by a qualified music teacher")
                            DisclaimerBullet(text: "Not intended for use as an official grade, assessment, or evaluation")
                            DisclaimerBullet(text: "Subject to limitations based on recording quality, background noise, and AI model capabilities")
                        }
                    }
                }

                PolicyCard(icon: "music.note", iconColor: .blue, title: "Music Recognition Disclaimer") {
                    VStack(alignment: .leading, spacing: 10) {
                        Text("Sheet music recognition uses computer vision and AI to interpret printed notation. Results may vary based on:")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)

                        VStack(alignment: .leading, spacing: 8) {
                            DisclaimerBullet(text: "Print quality and clarity of the original sheet music")
                            DisclaimerBullet(text: "Lighting conditions when scanning")
                            DisclaimerBullet(text: "Complexity of the musical arrangement")
                            DisclaimerBullet(text: "Handwritten vs. printed notation")
                        }

                        Text("Always verify recognized notes against your original sheet music before relying on playback.")
                            .font(.subheadline.weight(.medium))
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                            .padding(.top, 4)
                    }
                }

                PolicyCard(icon: "graduationcap.fill", iconColor: .purple, title: "Educational Tool — Not a Teacher") {
                    VStack(alignment: .leading, spacing: 10) {
                        Text("KITB is a supplemental practice tool. It does not:")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)

                        VStack(alignment: .leading, spacing: 8) {
                            DisclaimerBullet(text: "Teach you how to play a musical instrument")
                            DisclaimerBullet(text: "Replace instruction from a certified music teacher or band director")
                            DisclaimerBullet(text: "Provide professional music education or certification")
                            DisclaimerBullet(text: "Guarantee improvement in musical ability")
                        }

                        Text("For proper technique, posture, breath control, embouchure, and comprehensive musical development, always work with a qualified, certified music educator.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                            .padding(.top, 4)
                    }
                }

                PolicyCard(icon: "star.fill", iconColor: .yellow, title: "Grading & Assessment") {
                    Text("Scores and feedback provided by KITB are for personal reference and motivation only. They should not be used as official grades, submitted to teachers as proof of practice quality, or relied upon for any academic evaluation. KITB and its developers are not responsible for any grading decisions made by teachers, schools, or institutions based on information from this app.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }

                PolicyCard(icon: "bolt.shield.fill", iconColor: .teal, title: "Liability") {
                    Text("KITB and its developers, affiliates, and partners assume no responsibility or liability for any errors, omissions, or inaccuracies in music recognition, playback, or AI feedback. Use of this app is entirely at your own risk. By using KITB, you acknowledge and accept these limitations.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }

                contactFooter
            }
            .padding(.horizontal)
            .padding(.bottom, 40)
        }
        .background(Color(.systemGroupedBackground))
        .navigationTitle("Disclaimers")
        .navigationBarTitleDisplayMode(.inline)
    }

    private var importantDisclaimer: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 10) {
                Image(systemName: "exclamationmark.triangle.fill")
                    .font(.title3.weight(.semibold))
                    .foregroundStyle(.white)
                Text("Important Notice")
                    .font(.headline.bold())
                    .foregroundStyle(.white)
            }

            Text("KITB is a practice aid and learning tool designed to supplement — not replace — instruction from a qualified music teacher. All AI-generated feedback, scores, and music recognition results are approximate and should not be considered authoritative.")
                .font(.subheadline)
                .foregroundStyle(.white.opacity(0.9))
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(16)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            LinearGradient(
                colors: [.orange, .red.opacity(0.8)],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            ),
            in: .rect(cornerRadius: 16)
        )
    }

    private var contactFooter: some View {
        VStack(spacing: 8) {
            Text("Questions or concerns?")
                .font(.subheadline.weight(.semibold))
            Text("contact@m5capital.org")
                .font(.subheadline)
                .foregroundStyle(.blue)
        }
        .padding(.top, 8)
    }
}

struct DisclaimerBullet: View {
    let text: String

    var body: some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: "exclamationmark.circle.fill")
                .font(.caption)
                .foregroundStyle(.orange)
                .frame(width: 18)
                .padding(.top, 2)
            Text(text)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}
